# Generated by Django 3.0.5 on 2025-10-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
