# Generated by Django 3.0.5 on 2025-10-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_whatappmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatAppMessage',
            new_name='WhatsAppMessage',
        ),
    ]
