# Generated by Django 3.0.5 on 2025-10-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_auto_20251029_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('pulse', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('fbs', models.CharField(blank=True, max_length=20, null=True)),
                ('pbs', models.CharField(blank=True, max_length=20, null=True)),
                ('next_visit', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='MAA MEDICINE STORE', max_length=150)),
                ('address', models.CharField(default='STATION BAZAR, JAJPUR ROAD', max_length=200)),
                ('phone_numbers', models.CharField(default='9861182055, 8637219213', max_length=100)),
                ('doctor_name', models.CharField(default='DR. SANDEEP SAHU', max_length=150)),
                ('qualification', models.CharField(default='MD(MEDICINE), DM(ENDOCRINOLOGY)', max_length=200)),
                ('hospital_info', models.CharField(default='S.C.B. CUTTACK | ASST. PROF. ENDOCRINOLOGY, KIMS HOSPITAL, BHUBANESWAR', max_length=250)),
                ('consultation_info', models.CharField(default='CONSULTATION: EVERY 1ST SUNDAY', max_length=100)),
                ('reg_no', models.CharField(default='17780(O)', max_length=50)),
                ('footer_note', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
