# Generated by Django 3.0.5 on 2025-10-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_patientslip_storedesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedesign',
            name='consultation_info',
        ),
        migrations.RemoveField(
            model_name='storedesign',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='storedesign',
            name='hospital_info',
        ),
        migrations.RemoveField(
            model_name='storedesign',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='storedesign',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='storedesign',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
    ]
