# Generated by Django 5.2.7 on 2025-11-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hospital", "0006_auto_20251030_1208"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("department", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
