# Generated by Django 3.0.5 on 2025-11-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_appointment1'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='schedule_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Custom', 'Custom')], default='Custom', max_length=20),
        ),
    ]
