# Generated by Django 3.0.5 on 2025-11-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0008_doctorschedule_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='schedule_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Custom', 'Custom')], default='Daily', max_length=10),
        ),
    ]
