# Generated by Django 3.0.5 on 2025-11-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_auto_20251107_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientslip',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.Doctor'),
        ),
    ]
