# Generated by Django 3.0.5 on 2025-11-07 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_patientslip_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientslip',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.Doctor'),
        ),
    ]
