# Generated by Django 3.0.5 on 2025-11-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0012_messagecampaign_messagerecipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerecipient',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
        migrations.DeleteModel(
            name='MessageCampaign',
        ),
        migrations.DeleteModel(
            name='MessageRecipient',
        ),
    ]
